### ISSUE TITLE
Add option to disable the progress bar 

### ISSUE THREAD

**Issue by chschroeder** [huggingface/setfit#217]
Hi,

unless I missed something, it is currently not possible to disable the progress bar when training a SetFit model using `SetFitTrainer`. I suggest adding an option for this.

**Motivation**: I am using SetFit [in a Jupyter Notebook](https://github.com/webis-de/small-text/blob/5b5c5b6da1bdab44d0ff5974e177fc81e46f8f46/examples/notebooks/03-active-learning-with-setfit.ipynb) (not sure why it seems to print more than in the SetFit example notebook) and the output makes it rather ugly. Moreover, one might want not to display progress bars regardless of the notebook setting. 

**Problematic calls**:
https://github.com/huggingface/setfit/blob/fa1021d2355f0cb3a2c85732ee7ffe44b0cef0d1/src/setfit/trainer.py#L374
https://github.com/huggingface/setfit/blob/fa1021d2355f0cb3a2c85732ee7ffe44b0cef0d1/src/setfit/trainer.py#L388

**Comment by tomaarsen** [comment]
Perhaps a more appropriate fix is for [sentence-transformers](https://github.com/UKPLab/sentence-transformers) to start using [`tqdm.autonotebook`](https://tqdm.github.io/docs/shortcuts/#tqdmautonotebook), i.e.
```python
from tqdm.autonotebook import ...
```
rather than 
```python
from tqdm import ...
```

This will automatically detect whether `tqdm`, the module responsible for the bars, should display the progress as if it's in a console or as if it's in a Jupyter notebook. In a Jupyter notebook, the bars ought to look along the lines of this if `autonotebook` is used.

<img src="https://warehouse-camo.ingress.cmh1.psfhosted.org/2a5881775f59cf3461e0e1142a385cc5116b042d/68747470733a2f2f696d672e7471646d2e6d6c2f6a7570797465722d322e676966">

([Source](https://github.com/tqdm/tqdm#ipython-jupyter-integration))

This should be as simple as replacing all `from tqdm import ...` with `from tqdm.autonotebook import ...` in the sentence-transformers repository. 

- Tom Aarsen

**Comment by chschroeder** [comment]
Thanks for the quick response, @tomaarsen.

Yes, this sounds as sentence-transformers could improve on this as well. I did not know about `autonotebook`, this is great advice. Thank you (also for the detailed demonstration)!

In this case I feel SetFit could expose this parameter as well (at least as long as it explicitly passes the `show_progress_bar` parameter itself).

**Comment by tomaarsen** [comment]
Agreed. I've made a PR to handle the SetFit side of this issue, i.e. with `show_progress_bar`.

**Comment by chschroeder** [comment]
Awesome, thank you!

**Comment by kgourgou** [comment]
I get the pretty progress bars with the current version of SetFit, all I need to do is make sure `ipywidgets` is up-to-date and I use `from tqdm.auto import tqdm`. 

However, not being able to turn off all progress bars is an issue.
