### ISSUE TITLE
Contrastive training number of epochs

### ISSUE THREAD

**Issue by abhinav-kashyap-asus** [huggingface/setfit#256]
The `SentenceTransformer` number of epochs is the same as the number of epochs for the classification head. 
Even when `SetFitTrainer` is initialized with `num_epochs=1` and then `trainer.train(num_epochs=10)`, the sentence transformer runs with 10 epochs. Ideally, senatence transformer should run 1 epoch and the classifier should run for 10. 

The reason for this is that in `trainer.py`, the `model_body.fit()` is called with `num_epochs` rather than `self.num_epochs`. Is this intended??

I can write a PR to fix this if needed.

**Comment by tomaarsen** [comment]
Hello!

This is indeed intended. The optional arguments that can be passed to the trainer are intended to overwrite the "global" values set via the Trainer initialisation or by default. I'm afraid that in order to train the model with 1 epoch for the `SentenceTransformer` body and 10 epochs for the `SetFitHead`, then you must follow the end-to-end training example using `SetFitHead` from the README. 

In short:
```python
...

# Create trainer
trainer = SetFitTrainer(
    model=model,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    loss_class=CosineSimilarityLoss,
    metric="accuracy",
    batch_size=16,
    num_iterations=20, # The number of text pairs to generate for contrastive learning
    num_epochs=1, # The number of epochs to use for contrastive learning
    column_mapping={"sentence": "text", "label": "label"} # Map dataset columns to text/label expected by trainer
)

# Train and evaluate
trainer.freeze() # Freeze the head
trainer.train() # Train only the body

# Unfreeze the head and freeze the body -> head-only training
trainer.unfreeze(keep_body_frozen=True)
# or
# Unfreeze the head and unfreeze the body -> end-to-end training
trainer.unfreeze(keep_body_frozen=False)

trainer.train(
    num_epochs=25, # The number of epochs to train the head or the whole model (body and head)
    batch_size=16,
    body_learning_rate=1e-5, # The body's learning rate
    learning_rate=1e-2, # The head's learning rate
    l2_weight=0.0, # Weight decay on **both** the body and head. If `None`, will use 0.01.
)

metrics = trainer.evaluate()
```
This is far from ideal in my eyes. I believe that in no proper Trainer implementation should `trainer.train()` need to be called more than once. This is being worked on in #238.

Alternatively, you can use the logistic regression head, i.e. without `use_differentiable_head=True` in the model initialisation.

Hope that helps a bit.

- Tom Aarsen

**Comment by abhinav-kashyap-asus** [comment]
Thanks for the clarification :) Yes it is a bit confusing passing parameters in the instantiation of the model and in the `train()` function. 
As you note in #238 it is a bit problematic in creating new types of Head as well. 
One thing that you mentioned in another issue is that Multilabel classification cannot be performed with `SetfitHead`. That would require a completely different head, I suppose. Will wait for the refactoring work in #238 to go through. 

Also, are there any development guidelines for the repository. I have been tinkering around quite a bit and using Setfit as a git submodule for my own purposes. I would love to contribute if there is any guidelines

Thanks
Abhinav

**Comment by tomaarsen** [comment]
I'm afraid that there are no official development guidelines currently, other than the instructions at the bottom of the README: https://github.com/huggingface/setfit/#developer-installation
