### ISSUE TITLE
gradient_accumulation

### ISSUE THREAD

**Issue by zackduitz** [huggingface/setfit#389]
Is there a way in setFitTrainer to change the gradient_accumulation like you can do in the regular Trainer class in TrainingArguments? Also just in general I am looking for tips to make training faster.

**Comment by tomaarsen** [comment]
I'm afraid this isn't possible due to limitations from the [SentenceTransformer.fit](https://github.com/UKPLab/sentence-transformers/blob/179b659621c680371394d507683b25ba7faa0dd8/sentence_transformers/SentenceTransformer.py#L575) method.
To increase training speeds, you can lower the `num_iterations` to create less contrastive pairs to train with. Alternatively, you can increase the batch size to increase the training speed at the cost of higher memory usage while training.

- Tom Aarsen

**Comment by BecomeAllan** [comment]
the question here is... Handle [cuda out of memory] when the batch size in constrative learning dot fit in vram. What we can do ?
