### ISSUE TITLE
model_head.pkl not found on HuggingFace Hub

### ISSUE THREAD

**Issue by andysingal** [huggingface/setfit#409]
i got message:
"model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference."

is there something missing or is it normal?

**Comment by tomaarsen** [comment]
If you're loading a `SetFitModel` from a `SentenceTransformer` checkpoint, then this is totally normal. You should do training before you use the `SetFitModel`. 

If you're trying to load a pretrained `SetFitModel`, then this is not intentional. The `model_head.pkl` should store the SetFit classification head.

- Tom Aarsen

**Comment by tomaarsen** [comment]
I think this has been resolved, so I'll close it.
