### ISSUE TITLE
【question】could you tell me the latest embedding model which usable by setfit?

### ISSUE THREAD

**Issue by Yongtae723** [huggingface/setfit#436]
Hi!
This is not bug report but question.
From my understand, when we use SetFit, we have to choose one of embedding model from sentense transformer.
But now, I feel those models are kind of old and would like to know the latest model for embedding which can be used by setfit

Thank you in adv

**Comment by tomaarsen** [comment]
All models from the MTEB leaderboard can be used in SetFit (with exceptions of the ones that are just APIs): https://huggingface.co/spaces/mteb/leaderboard
Some notable models in particular:
* [BAAI/bge-large-en-v1.5](https://huggingface.co/BAAI/bge-large-en-v1.5), [BAAI/bge-base-en-v1.5](https://huggingface.co/BAAI/bge-base-en-v1.5), [BAAI/bge-small-en-v1.5](https://huggingface.co/BAAI/bge-small-en-v1.5): People within the embeddings field are quite excited about these.
* [jinaai/jina-embeddings-v2-base-en](https://huggingface.co/jinaai/jina-embeddings-v2-base-en) and [jinaai/jina-embeddings-v2-small-en](https://huggingface.co/jinaai/jina-embeddings-v2-small-en): These are recent models that people love for their large sequence length of 8192 tokens.
* [sentence-transformers/all-mpnet-base-v2](https://huggingface.co/sentence-transformers/all-mpnet-base-v2): An older, but still respected, model.
* [sentence-transformers/paraphrase-mpnet-base-v2](https://huggingface.co/sentence-transformers/paraphrase-mpnet-base-v2): I've used this one a lot in the past.

But most of all, feel free to experiment between models on MTEB. I'd love to hear your findings. For example, I don't know which metric from MTEB is most useful for SetFit. Also consider that beyond this leaderboard, some models may kind of arbitrarily perform better with specific domains due to their training data, so experimentation is useful!

- Tom Aarsen

**Comment by Yongtae723** [comment]
Oh great! thank you for the perfect answer.

as you said, I think there is no perfect embedding models for all use cases, so we have to experience it for the specific use case. 
I understand well, and thanks!
